stages:
  - build
  - test
  - deliver
default:
  image: registry.gitlab.akhcheck.ru/tp2024/registry/gcc:13
BuildCode:
  stage: build
  tags:
    - common
  script:
    - git clone https://github.com/google/googletest.git
    - cd gtest
    - mkdir build && cd build && cmake - DCMAKE_INSTALL_PREFIX=../dist && make && make install
  artifacts:
    untracked: false
    when: on_success
    expire_in: 8 days
    paths:
      - dist/

TestCode:
  stage: test
  tags:
    - common
  script:
    - cd build
    - ./tests

DeliverCode:
  stage: deliver
  tags:
    - common
  script:
    - cd build
    - cp bin/* /path/to/delivery/location/
