stages:
  - build
  - test
  - deliver
default:
  image: gcc
BuildCode:
  stage: build
  tags:
    - common
  before_script:
    - apt-get update
    - apt-get install -y cmake git
  script:
    - git clone https://github.com/google/googletest.git
    - cd googletest
    - mkdir build && cd build && cmake ..&& make && make install
  artifacts:
    untracked: false
    when: on_success
    expire_in: 8 days
    paths:
      - googletest/dist/

TestCode:
  stage: test
  tags:
    - common
  before_script:
    - apt-get update
    - apt-get install -y cmake
  script:
    - cd task-ci/bin
    - ./CTestEex --gtest_output=xml:report.xml
  artifacts:
    paths:
      - cd task-ci/bin
      - cd task-ci/lib
    reports:
      junit: task-ci/bin/report.xml

DeliverCode:
  stage: deliver
  tags:
    - common
  script:
    - cd build
    - cp bin/* /path/to/delivery/location/
