stages:
  - build
  - test
  - deliver
default:
  image: gcc
  tags:
    - common
BuildCode:
  stage: build
  before_script:
    - apt-get update
    - apt-get install -y cmake git
  script:
    - cd task-ci && cd 3rdparty
    - git clone https://github.com/google/googletest.git
    - cd googletest
    - mkdir build && cd build && cmake ..&& make && make install
    - cd ../../../
    - mkdir build && cd build
    - export GOOGLE_TEST_DIR=googletest
    - cmake .. && make
  artifacts:
    untracked: false
    when: on_success
    expire_in: 20 days
    paths:
      - task-ci/bin
      - task-ci/lib

TestCode:
  stage: test
  before_script:
    - apt-get update
    - apt-get install -y cmake
  script:
    - cd task-ci/bin
    - ./CTestExe --gtest_output=xml:report.xml
  artifacts:
    paths:
      - task-ci/lib
      - task-ci/bin
    reports:
      junit: task-ci/bin/report.xml

DeliverCode:
  stage: deliver
  script:
    - cd build
    - cp bin/* /path/to/delivery/location/
